[package]
name = "rust_cv"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.76"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
wasm-bindgen = "0.2.99"
yew = { version = "0.21.0", features = ["csr"] }
