name: "Deploy"
on:
  push:
  workflow_dispatch:

jobs:
  formatting:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown

      - name: Install Trunk
        run: cargo install trunk

      - uses: actions/setup-node@v4

      - name: Install TailwindCSS
        run: npm install -g tailwindcss

      - name: Build Project
        run: trunk build --release=true

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2

        with:
          playbook: deploy/run_deploy.yaml
          key: ${{ secrets.DEPLOY_KEY }}
          inventory: |
            [vadim_one]
            "${{ vars.host }}" ansible_port="${{ vars.port }}" ansible_user="${{ vars.user }}"
          requirements: deploy/galaxy-requirements.yml
